"""empty message

Revision ID: 2dbf63f71091
Revises: 6d0a5f587b13
Create Date: 2023-08-22 13:41:17.410072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dbf63f71091'
down_revision = '6d0a5f587b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.alter_column('has_cabinet',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.alter_column('has_cabinet',
               existing_type=sa.String(length=10),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
