"""empty message

Revision ID: 4b921188a153
Revises: a86fda39e1d9
Create Date: 2023-09-04 18:11:10.580767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b921188a153'
down_revision = 'a86fda39e1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equip_rack_ubication', sa.String(length=10), nullable=True))

    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rack_ubication', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.drop_column('rack_ubication')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_column('equip_rack_ubication')

    # ### end Alembic commands ###
