"""empty message

Revision ID: 58f821a72dc4
Revises: eddd9c25832a
Create Date: 2023-08-08 21:28:10.066506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f821a72dc4'
down_revision = 'eddd9c25832a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('rack_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('rack_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
