"""empty message

Revision ID: 71445c1f39a3
Revises: a46efb8168c5
Create Date: 2023-08-10 21:59:32.054716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71445c1f39a3'
down_revision = 'a46efb8168c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###
