"""empty message

Revision ID: 8819841c9355
Revises: 2cff56a76f54
Create Date: 2023-09-21 21:11:51.958370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8819841c9355'
down_revision = '2cff56a76f54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('serial',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('componentType',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.alter_column('componentType',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('serial',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('brand',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###
