"""empty message

Revision ID: 8d2fb40e73a3
Revises: 1d353a9f193a
Create Date: 2023-08-22 18:31:01.511548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d2fb40e73a3'
down_revision = '1d353a9f193a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=100), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
