"""empty message

Revision ID: 97971a2de864
Revises: c2d76ec51cf6
Create Date: 2023-09-02 13:18:07.922895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97971a2de864'
down_revision = 'c2d76ec51cf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('service_area',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('service_frontal',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('service_back',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('service_lateral',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('service_lateral',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('service_back',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('service_frontal',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
        batch_op.alter_column('service_area',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
