"""empty message

Revision ID: a46efb8168c5
Revises: c31cb0873a49
Create Date: 2023-08-10 21:46:21.605048

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a46efb8168c5'
down_revision = 'c31cb0873a49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('client_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rack_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'rack', ['rack_id'], ['id'])
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(None, 'description', ['description_id'], ['id'])

    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'description', ['description_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('create_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('description_id')

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rack_id')
        batch_op.drop_column('client_id')
        batch_op.drop_column('description_id')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('client_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
