"""empty message

Revision ID: ca5bca3ed0a2
Revises: 71445c1f39a3
Create Date: 2023-08-11 17:14:30.479749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca5bca3ed0a2'
down_revision = '71445c1f39a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.alter_column('number_part',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.alter_column('number_part',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
