"""empty message

Revision ID: cc2d4bf255c0
Revises: b4c6d825b511
Create Date: 2023-08-17 22:44:43.053148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc2d4bf255c0'
down_revision = 'b4c6d825b511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clientName', sa.String(length=255), nullable=False))
        batch_op.drop_constraint('client_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['clientName'])
        batch_op.drop_column('name')

    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('componentType', sa.String(length=100), nullable=True))

    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rack', schema=None) as batch_op:
        batch_op.alter_column('client_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.drop_column('componentType')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('client_name_key', ['name'])
        batch_op.drop_column('clientName')

    # ### end Alembic commands ###
