"""empty message

Revision ID: ec0b7839ff28
Revises: 89534c9f2667
Create Date: 2023-08-19 11:08:52.788081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec0b7839ff28'
down_revision = '89534c9f2667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anchor_type', sa.String(length=120), nullable=True))
        batch_op.drop_column('anchor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anchor', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('anchor_type')

    # ### end Alembic commands ###
