"""empty message

Revision ID: ff4bb71ac7ed
Revises: ec0b7839ff28
Create Date: 2023-08-19 11:30:19.693843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4bb71ac7ed'
down_revision = 'ec0b7839ff28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.drop_column('activity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
